// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
