default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.supabase[:host] %>
  port: <%= Rails.application.credentials.supabase[:port] %>
  database: <%= Rails.application.credentials.supabase[:database] %>
  username: <%= Rails.application.credentials.supabase[:user] %>
  password: <%= Rails.application.credentials.supabase[:password] %>
  sslmode: require
  prepared_statements: false
  advisory_locks: false

development:
  <<: *default

test:
  <<: *default
  database: <%= Rails.application.credentials.supabase[:test_database] %>

production:
  <<: *default

